package:
  name: msmb_data-dev
  version: "0.0.0"

source:
  path: ../../

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x

  run:
    - python
    - six
    - numpy x.x
    - scipy

test:
  requires:
    - nose
    - nose-timer
    - mdtraj
  imports:
    - msmb_data
  commands:
    - nosetests msmb_data -v --with-timer

about:
  home: https://github.com/msmbuilder
  license: LGPLv2.1+
  summary: 'Testing data for MSMBuilder'
