package:
  name: msmb_data
  version: "1.0.0.dev0"

source:
  path: ../../

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy

  run:
    - python
    - six
    - msmbuilder
    - numpy
    - scipy

test:
  requires:
    - nose
    - nose-timer
    - msmbuilder
    - mdtraj
  imports:
    - msmb_data
  commands:
    - nosetests msmb_data -v --with-timer

about:
  home: https://github.com/msmbuilder
  license: Apache Software License
  summary: 'Testing data for MSMBuilder'
